import {
    mdiAccount,
    mdiAccountGroup,
    mdiAccountPlus,
    mdiAlertCircleOutline,
    mdiArrowUpDropCircle,
    mdiAt,
    mdiAutorenew,
    mdiBell,
    mdiBookVariant,
    mdiBookVariantMultiple,
    mdiCalendar,
    mdiCalendarClock,
    mdiCardAccountDetailsOutline,
    mdiCellphone,
    mdiCertificateOutline,
    mdiChartBar,
    mdiCheckBold,
    mdiCheckCircleOutline,
    mdiClockOutline,
    mdiClose,
    mdiCloseCircleOutline,
    mdiCogOutline,
    mdiContentCopy,
    mdiContentSaveOutline,
    mdiDownload,
    mdiDrag,
    mdiDragVertical,
    mdiEarth,
    mdiEyedropper,
    mdiEyeOffOutline,
    mdiEyeOutline,
    mdiFaceAgent,
    mdiFileCodeOutline,
    mdiFileDocumentOutline,
    mdiFileExcelOutline,
    mdiFileEyeOutline,
    mdiFileImageOutline,
    mdiFileMusicOutline,
    mdiFileOutline,
    mdiFilePdfOutline,
    mdiFilePowerpointOutline,
    mdiFileTableOutline,
    mdiFileVideoOutline,
    mdiFileWordOutline,
    mdiFitToPageOutline,
    mdiFolderOutline,
    mdiFolderZipOutline,
    mdiFrequentlyAskedQuestions,
    mdiFullscreen,
    mdiFullscreenExit,
    mdiGraph,
    mdiHelp,
    mdiHelpCircleOutline,
    mdiHistory,
    mdiHome,
    mdiInformationOutline,
    mdiLanguageMarkdownOutline,
    mdiLoading,
    mdiLock,
    mdiLogout,
    mdiMagnify,
    mdiMagnifyMinusOutline,
    mdiMagnifyPlusOutline,
    mdiMenu,
    mdiMinus,
    mdiMonitor,
    mdiPencil,
    mdiPlus,
    mdiPlusCircle,
    mdiQrcode,
    mdiQrcodeScan,
    mdiRedoVariant,
    mdiShare,
    mdiSort,
    mdiSortAlphabeticalAscending,
    mdiSortAlphabeticalDescending,
    mdiSortAscending,
    mdiSortBoolAscending,
    mdiSortBoolDescending,
    mdiSortDescending,
    mdiSortNumericAscending,
    mdiSortNumericDescending,
    mdiSourceBranch,
    mdiSourceBranchMinus,
    mdiSourceBranchPlus,
    mdiSourceMerge,
    mdiStar,
    mdiStarCircleOutline,
    mdiStarOutline,
    mdiTableCog,
    mdiTableLarge,
    mdiTableRow,
    mdiTabletIpad,
    mdiTools,
    mdiTrashCanOutline,
    mdiUndoVariant,
    mdiUpdate,
    mdiWrench,
} from '@mdi/js';
import { languageIcons } from './language-icons';

export const icons = {
    about: { text: 'KoppaDb' },
    administrator: { path: mdiWrench },
    anonymous: { path: mdiEyeOffOutline },
    'authentication-email': {
        path: mdiCardAccountDetailsOutline,
        viewbox: '0 2 24 20',
    },
    boolean: { path: mdiCheckBold },
    changelog: { path: mdiUpdate },
    close: { path: mdiClose, viewbox: '4 4 16 16' },
    'column-order': { path: mdiTableCog },
    copy: { path: mdiContentCopy, viewbox: '2 0 22 24' },
    create: { path: mdiPlus, viewbox: '5 5 14 14' },
    date: { path: mdiCalendar },
    danger: { path: mdiCloseCircleOutline },
    'date-time': { path: mdiCalendarClock },
    delete: { path: mdiTrashCanOutline },
    download: { path: mdiDownload },
    drag: { path: mdiDrag },
    'drag-vertical': { path: mdiDragVertical, viewbox: '6 2 12 20' },
    edit: { path: mdiPencil },
    email: { path: mdiAt },
    entry: { path: mdiTableRow },
    fullscreenExit: { path: mdiFullscreenExit, viewbox: '4 4 16 16' },
    false: { path: mdiClose, viewbox: '4 4 16 16' },
    favorite: { path: mdiStar, viewbox: '2 2 20 20' },
    faq: { path: mdiFrequentlyAskedQuestions },
    features: { path: mdiStarCircleOutline },
    file: { path: mdiFileOutline },
    files: { path: mdiFolderOutline },
    'file-code': { path: mdiFileCodeOutline },
    'file-excel': { path: mdiFileExcelOutline },
    'file-image': { path: mdiFileImageOutline },
    'file-music': { path: mdiFileMusicOutline },
    'file-pdf': { path: mdiFilePdfOutline },
    'file-presentation': { path: mdiFilePowerpointOutline },
    'file-preview': { path: mdiFileEyeOutline },
    'file-table': { path: mdiFileTableOutline },
    'file-text': { path: mdiFileDocumentOutline },
    'file-video': { path: mdiFileVideoOutline },
    'file-word': { path: mdiFileWordOutline },
    'file-zip': { path: mdiFolderZipOutline },
    fit: { path: mdiFitToPageOutline },
    foreign: { path: mdiSourceBranch },
    foreignMultiple: { path: mdiSourceBranchPlus },
    foreignSingle: { path: mdiSourceBranch },
    fullscreen: { path: mdiFullscreen, viewbox: '4 4 16 16' },
    givePermissions: { path: mdiPlusCircle },
    help: { path: mdiHelpCircleOutline },
    history: { path: mdiHistory, viewbox: '0 2 22 20' },
    home: { path: mdiHome, viewbox: '2 2 22 18' },
    info: { path: mdiInformationOutline },
    inviteUsers: { path: mdiAccountPlus },
    layout: { path: mdiGraph },
    'landing-page-secure': { path: mdiLock, viewbox: '4 1 16 21' },
    'landing-page-monitor': { path: mdiMonitor, viewbox: '1 2 22 20' },
    'landing-page-cellphone': {
        path: mdiCellphone,
        viewbox: '5 1 14 22',
    },
    'landing-page-tablet-ipad': {
        path: mdiTabletIpad,
        viewbox: '2 0 19 24',
    },
    licenses: { path: mdiCertificateOutline, viewbox: '2 2 20 20' },
    'list-input': { path: mdiMenu },
    loading: { path: mdiLoading, spinning: true },
    logout: { path: mdiLogout },
    markdown: { path: mdiLanguageMarkdownOutline, viewbox: '2 6 20 12' },
    minus: { path: mdiMinus },
    'not-favorite': { path: mdiStarOutline, viewbox: '2 2 20 20' },
    'notification-email': { path: mdiBell },
    null: { path: mdiHelp },
    'node-expand': { path: mdiSourceBranchPlus },
    'node-remove': { path: mdiSourceBranchMinus },
    'node-inspect': { path: mdiEyedropper },
    number: { text: '42' },
    overview: { path: mdiEarth },
    permissions: { path: mdiLock, viewbox: '0 0 24 24' },
    plus: { path: mdiPlus, viewbox: '5 5 14 14' },
    project: { path: mdiBookVariant },
    'project-overview': { path: mdiEarth },
    projects: { path: mdiBookVariantMultiple },
    'public-email': { path: mdiEarth },
    qrcode: { path: mdiQrcode, viewbox: '2 2 20 20' },
    'relation-explorer': { path: mdiSourceMerge },
    reset: { path: mdiUndoVariant, viewbox: '2 2 20 18' },
    restore: { path: mdiRedoVariant },
    save: { path: mdiContentSaveOutline },
    scanner: { path: mdiQrcodeScan, viewbox: '0 0 24 24' },
    'scroll-to-top': { path: mdiArrowUpDropCircle },
    search: { path: mdiMagnify },
    settings: { path: mdiCogOutline },
    share: { path: mdiShare },
    sort: { path: mdiSort },
    'sort-asc': { path: mdiSortAscending },
    'sort-boolean': { path: mdiSort },
    'sort-boolean-asc': { path: mdiSortBoolAscending },
    'sort-boolean-desc': { path: mdiSortBoolDescending },
    'sort-desc': { path: mdiSortDescending },
    'sort-number': { path: mdiSort },
    'sort-number-asc': { path: mdiSortNumericAscending },
    'sort-number-desc': { path: mdiSortNumericDescending },
    'sort-string': { path: mdiSort },
    'sort-string-asc': { path: mdiSortAlphabeticalAscending },
    'sort-string-desc': { path: mdiSortAlphabeticalDescending },
    statistics: { path: mdiChartBar },
    string: { text: 'ABC' },
    success: { path: mdiCheckCircleOutline },
    support: { path: mdiFaceAgent },
    synchronize: { path: mdiAutorenew, viewbox: '4 1 16 22' },
    synchronizing: { path: mdiAutorenew, spinning: true },
    table: { path: mdiTableLarge },
    'tables-editor': { path: mdiTools },
    text: { text: 'TXT' },
    time: { path: mdiClockOutline },
    true: { path: mdiCheckBold },
    url: { text: 'URL' },
    user: { path: mdiAccount, viewbox: '4 4 16 16' },
    users: { path: mdiAccountGroup },
    invisible: { path: mdiEyeOffOutline },
    visible: { path: mdiEyeOutline },
    warning: { path: mdiAlertCircleOutline },
    'zoom-in': { path: mdiMagnifyPlusOutline },
    'zoom-out': { path: mdiMagnifyMinusOutline },
    ...languageIcons,
};
